-- MySQL Script generated by MySQL Workbench
-- Tue Mar  7 17:18:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `academia` ;

-- -----------------------------------------------------
-- Table `academia`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `foto` BLOB(255) NULL,
  `nome` VARCHAR(255) NULL,
  `observacao` VARCHAR(255) NULL,
  `dataCadastro` DATE NULL,
  `idcadastrador` INT NOT NULL,
  PRIMARY KEY (`idpessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`usuario_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`usuario_grupo` (
  `idusuario_grupo` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(255) NULL,
  PRIMARY KEY (`idusuario_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `idusuario_grupo` INT NOT NULL,
  `usuario` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`idusuario`, `idpessoa`, `idusuario_grupo`),
  INDEX `fk_usuario_pessoa1_idx` (`idpessoa` ASC),
  INDEX `fk_usuario_usuario_grupo1_idx` (`idusuario_grupo` ASC),
  CONSTRAINT `fk_usuario_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `academia`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_usuario_grupo1`
    FOREIGN KEY (`idusuario_grupo`)
    REFERENCES `academia`.`usuario_grupo` (`idusuario_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `funcao` VARCHAR(255) NULL,
  `setor` VARCHAR(255) NULL,
  `dataAdmissao` DATE NULL,
  `ctps` VARCHAR(255) NULL,
  `serie` VARCHAR(255) NULL,
  `pis` VARCHAR(255) NULL,
  `salarioBase` DOUBLE NULL,
  PRIMARY KEY (`idfuncionario`, `idpessoa`),
  INDEX `fk_funcionario_pessoa1_idx` (`idpessoa` ASC),
  CONSTRAINT `fk_funcionario_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `academia`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `codigo_ibge` VARCHAR(255) NULL,
  `sigla` VARCHAR(255) NULL,
  `estado` VARCHAR(255) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`cidade` (
  `idcidade` INT NOT NULL AUTO_INCREMENT,
  `idestado` INT NOT NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idcidade`, `idestado`),
  INDEX `fk_cidade_estado1_idx` (`idestado` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`idestado`)
    REFERENCES `academia`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`bairro` (
  `idbairro` INT NOT NULL AUTO_INCREMENT,
  `idcidade` INT NOT NULL,
  `bairro` VARCHAR(255) NULL,
  PRIMARY KEY (`idbairro`, `idcidade`),
  INDEX `fk_bairro_cidade1_idx` (`idcidade` ASC),
  CONSTRAINT `fk_bairro_cidade1`
    FOREIGN KEY (`idcidade`)
    REFERENCES `academia`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `idbairro` INT NOT NULL,
  `rua` VARCHAR(255) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(255) NULL,
  `referencia` VARCHAR(255) NULL,
  `cep` VARCHAR(255) NULL,
  PRIMARY KEY (`idendereco`, `idpessoa`, `idbairro`),
  INDEX `fk_endereco_pessoa1_idx` (`idpessoa` ASC),
  INDEX `fk_endereco_bairro1_idx` (`idbairro` ASC),
  CONSTRAINT `fk_endereco_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `academia`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_bairro1`
    FOREIGN KEY (`idbairro`)
    REFERENCES `academia`.`bairro` (`idbairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`parq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`parq` (
  `idparq` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL,
  `textoParq` TEXT(10000) NULL,
  PRIMARY KEY (`idparq`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`perguntas_parq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`perguntas_parq` (
  `idperguntaParq` INT NOT NULL AUTO_INCREMENT,
  `idparq` INT NOT NULL,
  `pergunta` TEXT(5000) NULL,
  PRIMARY KEY (`idperguntaParq`, `idparq`),
  INDEX `fk_perguntas_parq_parq1_idx` (`idparq` ASC),
  CONSTRAINT `fk_perguntas_parq_parq1`
    FOREIGN KEY (`idparq`)
    REFERENCES `academia`.`parq` (`idparq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `consultor` INT NULL,
  `codigoCatraca` VARCHAR(255) NULL,
  PRIMARY KEY (`idaluno`, `idpessoa`),
  INDEX `fk_aluno_pessoa1_idx` (`idpessoa` ASC),
  CONSTRAINT `fk_aluno_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `academia`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`parq_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`parq_aluno` (
  `idparqAluno` INT NOT NULL AUTO_INCREMENT,
  `idaluno` INT NOT NULL,
  PRIMARY KEY (`idparqAluno`, `idaluno`),
  INDEX `fk_parq_aluno_aluno1_idx` (`idaluno` ASC),
  CONSTRAINT `fk_parq_aluno_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `academia`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `razaoSocial` VARCHAR(255) NULL,
  `cnpj` VARCHAR(255) NULL,
  `inscricaoEstadual` VARCHAR(255) NULL,
  PRIMARY KEY (`idFornecedor`, `idpessoa`),
  INDEX `fk_Fornecedor_pessoa1_idx` (`idpessoa` ASC),
  CONSTRAINT `fk_Fornecedor_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `academia`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`email` (
  `idemail` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`idemail`, `idpessoa`),
  INDEX `fk_email_pessoa1_idx` (`idpessoa` ASC),
  CONSTRAINT `fk_email_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `academia`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`telefone` (
  `idtelefone` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `tipo` VARCHAR(255) NULL,
  `operadora` VARCHAR(255) NULL,
  `telefone` VARCHAR(255) NULL,
  `contato` VARCHAR(255) NULL,
  PRIMARY KEY (`idtelefone`, `idpessoa`),
  INDEX `fk_telefone_pessoa1_idx` (`idpessoa` ASC),
  CONSTRAINT `fk_telefone_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `academia`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`prazo_plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`prazo_plano` (
  `idprazoPlano` INT NOT NULL AUTO_INCREMENT,
  `prazoPlano` VARCHAR(255) NULL,
  PRIMARY KEY (`idprazoPlano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`tipo_plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`tipo_plano` (
  `idtipoPlano` INT NOT NULL AUTO_INCREMENT,
  `tipoPlano` VARCHAR(255) NULL,
  PRIMARY KEY (`idtipoPlano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`forma_pagamento` (
  `idformaPagamento` INT NOT NULL AUTO_INCREMENT,
  `formaPagamento` VARCHAR(255) NULL,
  PRIMARY KEY (`idformaPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`categoria_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`categoria_treino` (
  `idcategoriaTreino` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(255) NULL,
  PRIMARY KEY (`idcategoriaTreino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`contrato_plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`contrato_plano` (
  `idcontrato` INT NOT NULL AUTO_INCREMENT,
  `idaluno` INT NOT NULL,
  `idcategoriaTreino` INT NOT NULL,
  `idtipoPlano` INT NOT NULL,
  `idprazoPlano` INT NOT NULL,
  `idformaPagamento` INT NOT NULL,
  `numeroParcelas` INT NULL,
  `valorParcela` DOUBLE NULL,
  `valorTotal` DOUBLE NULL,
  `dataPagamento` DATE NULL,
  `dataContratacao` DATE NULL,
  `dataTermino` DATE NULL,
  `dataRenovacao` DATE NULL,
  PRIMARY KEY (`idcontrato`, `idaluno`, `idcategoriaTreino`, `idtipoPlano`, `idprazoPlano`, `idformaPagamento`),
  INDEX `fk_contrato_aluno1_idx` (`idaluno` ASC),
  INDEX `fk_contrato_plano_prazo_plano1_idx` (`idprazoPlano` ASC),
  INDEX `fk_contrato_plano_tipo_plano1_idx` (`idtipoPlano` ASC),
  INDEX `fk_contrato_plano_forma_pagamento1_idx` (`idformaPagamento` ASC),
  INDEX `fk_contrato_plano_categoria_treino1_idx` (`idcategoriaTreino` ASC),
  CONSTRAINT `fk_contrato_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `academia`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_plano_prazo_plano1`
    FOREIGN KEY (`idprazoPlano`)
    REFERENCES `academia`.`prazo_plano` (`idprazoPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_plano_tipo_plano1`
    FOREIGN KEY (`idtipoPlano`)
    REFERENCES `academia`.`tipo_plano` (`idtipoPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_plano_forma_pagamento1`
    FOREIGN KEY (`idformaPagamento`)
    REFERENCES `academia`.`forma_pagamento` (`idformaPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_plano_categoria_treino1`
    FOREIGN KEY (`idcategoriaTreino`)
    REFERENCES `academia`.`categoria_treino` (`idcategoriaTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`treino_sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`treino_sessao` (
  `idtreinoSessao` INT NOT NULL AUTO_INCREMENT,
  `sessao` VARCHAR(255) NULL,
  PRIMARY KEY (`idtreinoSessao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`cagoria_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`cagoria_treino` (
  `idcagoriaTreino` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(255) NULL,
  PRIMARY KEY (`idcagoriaTreino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`modalidade_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`modalidade_treino` (
  `idmodalidadeTreino` INT NOT NULL AUTO_INCREMENT,
  `modalidade` VARCHAR(255) NULL,
  PRIMARY KEY (`idmodalidadeTreino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`regiao_trabalhada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`regiao_trabalhada` (
  `idregiaoTrabalhada` INT NOT NULL AUTO_INCREMENT,
  `regiaoTrabalhada` VARCHAR(255) NULL,
  `idcadastrador` INT NOT NULL,
  `dataCadastro` DATE NULL,
  PRIMARY KEY (`idregiaoTrabalhada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`tipo_exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`tipo_exercicio` (
  `idtipoExercicio` INT NOT NULL AUTO_INCREMENT,
  `tipoExercicio` VARCHAR(255) NULL,
  `idcadastrador` INT NOT NULL,
  `dataCadastro` DATE NULL,
  PRIMARY KEY (`idtipoExercicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aparelho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aparelho` (
  `idaparelho` INT NOT NULL AUTO_INCREMENT,
  `aparelho` VARCHAR(255) NULL,
  `numero` VARCHAR(255) NULL,
  `idcadastrador` INT NOT NULL,
  `dataCadastro` DATE NULL,
  PRIMARY KEY (`idaparelho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`exercicio` (
  `idexercicio` INT NOT NULL AUTO_INCREMENT,
  `idtipoExercicio` INT NOT NULL,
  `idregiaoTrabalhada` INT NOT NULL,
  `idaparelho` INT NOT NULL,
  `exercicio` VARCHAR(255) NULL,
  `idcadastrador` INT NOT NULL,
  `dataCadastro` DATE NULL,
  PRIMARY KEY (`idexercicio`, `idtipoExercicio`, `idregiaoTrabalhada`, `idaparelho`),
  INDEX `fk_exercicio_regiao_trabalhada1_idx` (`idregiaoTrabalhada` ASC),
  INDEX `fk_exercicio_tipo_exercicio1_idx` (`idtipoExercicio` ASC),
  INDEX `fk_exercicio_aparelho1_idx` (`idaparelho` ASC),
  CONSTRAINT `fk_exercicio_regiao_trabalhada1`
    FOREIGN KEY (`idregiaoTrabalhada`)
    REFERENCES `academia`.`regiao_trabalhada` (`idregiaoTrabalhada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercicio_tipo_exercicio1`
    FOREIGN KEY (`idtipoExercicio`)
    REFERENCES `academia`.`tipo_exercicio` (`idtipoExercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercicio_aparelho1`
    FOREIGN KEY (`idaparelho`)
    REFERENCES `academia`.`aparelho` (`idaparelho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`nivel` (
  `idnivel` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(255) NULL,
  PRIMARY KEY (`idnivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`treino` (
  `idtreino` INT NOT NULL AUTO_INCREMENT,
  `treino` VARCHAR(255) NULL,
  `regioesTrabalhadas` VARCHAR(255) NULL,
  PRIMARY KEY (`idtreino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`velocidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`velocidade` (
  `idvelocidade` INT NOT NULL AUTO_INCREMENT,
  `velocidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idvelocidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`carga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`carga` (
  `idcarga` INT NOT NULL AUTO_INCREMENT,
  `carga` INT NULL,
  PRIMARY KEY (`idcarga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`serie` (
  `idserie` INT NOT NULL AUTO_INCREMENT,
  `serie` INT NULL,
  PRIMARY KEY (`idserie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`repeticoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`repeticoes` (
  `idrepeticoes` INT NOT NULL AUTO_INCREMENT,
  `numeroRepeticao` INT NULL,
  PRIMARY KEY (`idrepeticoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`treino_exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`treino_exercicio` (
  `idtreinoExercicio` INT NOT NULL AUTO_INCREMENT,
  `idtreino` INT NOT NULL,
  `idexercicio` INT NOT NULL,
  `idtreinoSessao` INT NOT NULL,
  PRIMARY KEY (`idtreinoExercicio`, `idtreino`, `idexercicio`, `idtreinoSessao`),
  INDEX `fk_treino_has_exercicio_exercicio1_idx` (`idexercicio` ASC),
  INDEX `fk_treino_has_exercicio_treino1_idx` (`idtreino` ASC),
  INDEX `fk_treino_exercicio_treino_sessao1_idx` (`idtreinoSessao` ASC),
  CONSTRAINT `fk_treino_has_exercicio_treino1`
    FOREIGN KEY (`idtreino`)
    REFERENCES `academia`.`treino` (`idtreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_treino_has_exercicio_exercicio1`
    FOREIGN KEY (`idexercicio`)
    REFERENCES `academia`.`exercicio` (`idexercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_treino_exercicio_treino_sessao1`
    FOREIGN KEY (`idtreinoSessao`)
    REFERENCES `academia`.`treino_sessao` (`idtreinoSessao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`table` (
  `idtable` INT NOT NULL,
  PRIMARY KEY (`idtable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`treino_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`treino_aluno` (
  `idTreinoAluno` INT NOT NULL AUTO_INCREMENT,
  `idtreino` INT NOT NULL,
  `idaluno` INT NOT NULL,
  `dataInicio` DATE NULL,
  `dataFim` DATE NULL,
  PRIMARY KEY (`idTreinoAluno`, `idtreino`, `idaluno`),
  INDEX `fk_treino_has_aluno_aluno1_idx` (`idaluno` ASC),
  INDEX `fk_treino_has_aluno_treino1_idx` (`idtreino` ASC),
  CONSTRAINT `fk_treino_has_aluno_treino1`
    FOREIGN KEY (`idtreino`)
    REFERENCES `academia`.`treino` (`idtreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_treino_has_aluno_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `academia`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`exercicio_repeticoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`exercicio_repeticoes` (
  `idexercicioRepeticoes` INT NOT NULL AUTO_INCREMENT,
  `idexercicio` INT NOT NULL,
  `idrepeticoes` INT NOT NULL,
  PRIMARY KEY (`idexercicioRepeticoes`, `idexercicio`, `idrepeticoes`),
  INDEX `fk_exercicio_has_repeticoes_repeticoes1_idx` (`idrepeticoes` ASC),
  INDEX `fk_exercicio_has_repeticoes_exercicio1_idx` (`idexercicio` ASC),
  CONSTRAINT `fk_exercicio_has_repeticoes_exercicio1`
    FOREIGN KEY (`idexercicio`)
    REFERENCES `academia`.`exercicio` (`idexercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercicio_has_repeticoes_repeticoes1`
    FOREIGN KEY (`idrepeticoes`)
    REFERENCES `academia`.`repeticoes` (`idrepeticoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`exercicio_carga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`exercicio_carga` (
  `idexercicioCarga` INT NOT NULL AUTO_INCREMENT,
  `idexercicio` INT NOT NULL,
  `idcarga` INT NOT NULL,
  PRIMARY KEY (`idexercicioCarga`, `idexercicio`, `idcarga`),
  INDEX `fk_exercicio_has_carga_carga1_idx` (`idcarga` ASC),
  INDEX `fk_exercicio_has_carga_exercicio1_idx` (`idexercicio` ASC),
  CONSTRAINT `fk_exercicio_has_carga_exercicio1`
    FOREIGN KEY (`idexercicio`)
    REFERENCES `academia`.`exercicio` (`idexercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercicio_has_carga_carga1`
    FOREIGN KEY (`idcarga`)
    REFERENCES `academia`.`carga` (`idcarga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`exercicio_serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`exercicio_serie` (
  `idexercicioSerie` INT NOT NULL AUTO_INCREMENT,
  `idexercicio` INT NOT NULL,
  `idserie` INT NOT NULL,
  PRIMARY KEY (`idexercicioSerie`, `idexercicio`, `idserie`),
  INDEX `fk_exercicio_has_serie_serie1_idx` (`idserie` ASC),
  INDEX `fk_exercicio_has_serie_exercicio1_idx` (`idexercicio` ASC),
  CONSTRAINT `fk_exercicio_has_serie_exercicio1`
    FOREIGN KEY (`idexercicio`)
    REFERENCES `academia`.`exercicio` (`idexercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercicio_has_serie_serie1`
    FOREIGN KEY (`idserie`)
    REFERENCES `academia`.`serie` (`idserie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`exercicio_has_velocidade_exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`exercicio_has_velocidade_exercicio` (
  `idexercicio` INT NOT NULL,
  `idvelocidadeExercicio` INT NOT NULL,
  PRIMARY KEY (`idexercicio`, `idvelocidadeExercicio`),
  INDEX `fk_exercicio_has_velocidade_exercicio_velocidade_exercicio1_idx` (`idvelocidadeExercicio` ASC),
  INDEX `fk_exercicio_has_velocidade_exercicio_exercicio1_idx` (`idexercicio` ASC),
  CONSTRAINT `fk_exercicio_has_velocidade_exercicio_exercicio1`
    FOREIGN KEY (`idexercicio`)
    REFERENCES `academia`.`exercicio` (`idexercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercicio_has_velocidade_exercicio_velocidade_exercicio1`
    FOREIGN KEY (`idvelocidadeExercicio`)
    REFERENCES `academia`.`velocidade` (`idvelocidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`exercicio_velocidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`exercicio_velocidade` (
  `idvelocidadeExercicio` INT NOT NULL AUTO_INCREMENT,
  `idexercicio` INT NOT NULL,
  `idvelocidade` INT NOT NULL,
  PRIMARY KEY (`idvelocidadeExercicio`, `idexercicio`, `idvelocidade`),
  INDEX `fk_exercicio_has_velocidade_velocidade1_idx` (`idvelocidade` ASC),
  INDEX `fk_exercicio_has_velocidade_exercicio1_idx` (`idexercicio` ASC),
  CONSTRAINT `fk_exercicio_has_velocidade_exercicio1`
    FOREIGN KEY (`idexercicio`)
    REFERENCES `academia`.`exercicio` (`idexercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercicio_has_velocidade_velocidade1`
    FOREIGN KEY (`idvelocidade`)
    REFERENCES `academia`.`velocidade` (`idvelocidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`parq_aluno_perguntas_parq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`parq_aluno_perguntas_parq` (
  `idparq_aluno_perguntas_parq` INT NOT NULL AUTO_INCREMENT,
  `idparqAluno` INT NOT NULL,
  `idperguntaParq` INT NOT NULL,
  `resposta` TINYINT(1) NULL,
  PRIMARY KEY (`idparq_aluno_perguntas_parq`, `idparqAluno`, `idperguntaParq`),
  INDEX `fk_parq_aluno_has_perguntas_parq_perguntas_parq1_idx` (`idperguntaParq` ASC),
  INDEX `fk_parq_aluno_has_perguntas_parq_parq_aluno1_idx` (`idparqAluno` ASC),
  CONSTRAINT `fk_parq_aluno_has_perguntas_parq_parq_aluno1`
    FOREIGN KEY (`idparqAluno`)
    REFERENCES `academia`.`parq_aluno` (`idparqAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parq_aluno_has_perguntas_parq_perguntas_parq1`
    FOREIGN KEY (`idperguntaParq`)
    REFERENCES `academia`.`perguntas_parq` (`idperguntaParq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`pessoaFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`pessoaFisica` (
  `idpessoaFisica` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `dataNascimento` DATE NULL,
  `cpf` VARCHAR(255) NULL,
  `rg` VARCHAR(255) NULL,
  `genero` VARCHAR(255) NULL,
  `estadoCivil` VARCHAR(255) NULL,
  `profissao` VARCHAR(255) NULL,
  PRIMARY KEY (`idpessoaFisica`, `idpessoa`),
  INDEX `fk_pessoaFisica_pessoa1_idx` (`idpessoa` ASC),
  CONSTRAINT `fk_pessoaFisica_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `academia`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`pessoaJuridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`pessoaJuridica` (
  `idpessoaJuridica` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `razaoSocial` VARCHAR(255) NULL,
  `cnpj` VARCHAR(255) NULL,
  `inscricaoEstadual` VARCHAR(255) NULL,
  PRIMARY KEY (`idpessoaJuridica`, `idpessoa`),
  INDEX `fk_pessoaJuridica_pessoa1_idx` (`idpessoa` ASC),
  CONSTRAINT `fk_pessoaJuridica_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `academia`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`modalidade` (
  `idmodalidade` INT NOT NULL AUTO_INCREMENT,
  `idcategoriaTreino` INT NOT NULL,
  `modalidade` VARCHAR(255) NULL,
  PRIMARY KEY (`idmodalidade`, `idcategoriaTreino`),
  INDEX `fk_modalidade_categoria_treino1_idx` (`idcategoriaTreino` ASC),
  CONSTRAINT `fk_modalidade_categoria_treino1`
    FOREIGN KEY (`idcategoriaTreino`)
    REFERENCES `academia`.`categoria_treino` (`idcategoriaTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`categoria_treino_has_modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`categoria_treino_has_modalidade` (
  `idCategoriaModalidade` INT NOT NULL AUTO_INCREMENT,
  `idcategoriaTreino` INT NOT NULL,
  `idmodalidadeTreino` INT NOT NULL,
  PRIMARY KEY (`idCategoriaModalidade`, `idcategoriaTreino`, `idmodalidadeTreino`),
  INDEX `fk_categoria_treino_has_modalidade_modalidade1_idx` (`idCategoriaModalidade` ASC),
  INDEX `fk_categoria_treino_has_modalidade_categoria_treino1_idx` (`idcategoriaTreino` ASC, `idmodalidadeTreino` ASC),
  CONSTRAINT `fk_categoria_treino_has_modalidade_categoria_treino1`
    FOREIGN KEY (`idcategoriaTreino`)
    REFERENCES `academia`.`categoria_treino` (`idcategoriaTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_treino_has_modalidade_modalidade1`
    FOREIGN KEY (`idCategoriaModalidade`)
    REFERENCES `academia`.`modalidade` (`idmodalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`contrato` (
  `idcontrato` INT NOT NULL AUTO_INCREMENT,
  `texto` LONGBLOB NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`idcontrato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno_contrato` (
  `idaluno_contrato` INT NOT NULL,
  `idcontratoPlano` INT NOT NULL,
  `idcontrato` INT NOT NULL,
  PRIMARY KEY (`idaluno_contrato`, `idcontratoPlano`, `idcontrato`),
  INDEX `fk_contrato_plano_has_contrato_contrato1_idx` (`idcontrato` ASC),
  INDEX `fk_contrato_plano_has_contrato_contrato_plano1_idx` (`idcontratoPlano` ASC),
  CONSTRAINT `fk_contrato_plano_has_contrato_contrato_plano1`
    FOREIGN KEY (`idcontratoPlano`)
    REFERENCES `academia`.`contrato_plano` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_plano_has_contrato_contrato1`
    FOREIGN KEY (`idcontrato`)
    REFERENCES `academia`.`contrato` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno_contrato` (
  `idaluno_contrato` INT NOT NULL,
  `idcontratoPlano` INT NOT NULL,
  `idcontrato` INT NOT NULL,
  PRIMARY KEY (`idaluno_contrato`, `idcontratoPlano`, `idcontrato`),
  INDEX `fk_contrato_plano_has_contrato_contrato1_idx` (`idcontrato` ASC),
  INDEX `fk_contrato_plano_has_contrato_contrato_plano1_idx` (`idcontratoPlano` ASC),
  CONSTRAINT `fk_contrato_plano_has_contrato_contrato_plano1`
    FOREIGN KEY (`idcontratoPlano`)
    REFERENCES `academia`.`contrato_plano` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_plano_has_contrato_contrato1`
    FOREIGN KEY (`idcontrato`)
    REFERENCES `academia`.`contrato` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`table1` (
  `idtable1` INT NOT NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`ciclo` (
  `idciclo` INT NOT NULL AUTO_INCREMENT,
  `ciclo` VARCHAR(255) NULL,
  `nivel` VARCHAR(255) NULL,
  `genero` VARCHAR(255) NULL,
  `metaPrincipal` VARCHAR(255) NULL,
  `modeloCiclo` VARCHAR(255) NULL,
  `idcadastrador` INT NOT NULL,
  `dataCadastro` DATE NULL,
  PRIMARY KEY (`idciclo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`treino` (
  `idtreino` INT NOT NULL AUTO_INCREMENT,
  `treino` VARCHAR(255) NULL,
  `regioesTrabalhadas` VARCHAR(255) NULL,
  PRIMARY KEY (`idtreino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`ciclo_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`ciclo_treino` (
  `idCiclo_treino` INT NOT NULL AUTO_INCREMENT,
  `Ciclo_idciclo` INT NOT NULL,
  `treino_idtreino` INT NOT NULL,
  PRIMARY KEY (`idCiclo_treino`, `Ciclo_idciclo`, `treino_idtreino`),
  INDEX `fk_Ciclo_has_treino_treino1_idx` (`treino_idtreino` ASC),
  INDEX `fk_Ciclo_has_treino_Ciclo1_idx` (`Ciclo_idciclo` ASC),
  CONSTRAINT `fk_Ciclo_has_treino_Ciclo1`
    FOREIGN KEY (`Ciclo_idciclo`)
    REFERENCES `academia`.`ciclo` (`idciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ciclo_has_treino_treino1`
    FOREIGN KEY (`treino_idtreino`)
    REFERENCES `academia`.`treino` (`idtreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`exercicio_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`exercicio_treino` (
  `idexercicio_treino` INT NOT NULL AUTO_INCREMENT,
  `exercicio_idexercicio` INT NOT NULL,
  `treino_idtreino` INT NOT NULL,
  PRIMARY KEY (`idexercicio_treino`, `exercicio_idexercicio`, `treino_idtreino`),
  INDEX `fk_exercicio_has_treino_treino1_idx` (`treino_idtreino` ASC),
  INDEX `fk_exercicio_has_treino_exercicio1_idx` (`exercicio_idexercicio` ASC),
  CONSTRAINT `fk_exercicio_has_treino_exercicio1`
    FOREIGN KEY (`exercicio_idexercicio`)
    REFERENCES `academia`.`exercicio` (`idexercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercicio_has_treino_treino1`
    FOREIGN KEY (`treino_idtreino`)
    REFERENCES `academia`.`treino` (`idtreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`exercicio_combinado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`exercicio_combinado` (
  `idexercicio_combinado` INT NOT NULL AUTO_INCREMENT,
  `idexercicio_treino` INT NOT NULL,
  `idexercicio` INT NOT NULL,
  PRIMARY KEY (`idexercicio_combinado`, `idexercicio_treino`, `idexercicio`),
  INDEX `fk_exercicio_combinado_exercicio_treino1_idx` (`idexercicio_treino` ASC),
  CONSTRAINT `fk_exercicio_combinado_exercicio_treino1`
    FOREIGN KEY (`idexercicio_treino`)
    REFERENCES `academia`.`exercicio_treino` (`idexercicio_treino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno_ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno_ciclo` (
  `idaluno_ciclo` INT NOT NULL AUTO_INCREMENT,
  `idaluno` INT NOT NULL,
  `ciclo` VARCHAR(255) NULL,
  `nivel` VARCHAR(255) NULL,
  `genero` VARCHAR(255) NULL,
  `metaPrincipal` VARCHAR(255) NULL,
  `modeloCiclo` VARCHAR(255) NULL,
  `data_inicio` DATE NULL,
  `data_termino` DATE NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`idaluno_ciclo`, `idaluno`),
  INDEX `fk_aluno_ciclo_aluno1_idx` (`idaluno` ASC),
  CONSTRAINT `fk_aluno_ciclo_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `academia`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno_ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno_ciclo` (
  `idaluno_ciclo` INT NOT NULL AUTO_INCREMENT,
  `idaluno` INT NOT NULL,
  `ciclo` VARCHAR(255) NULL,
  `nivel` VARCHAR(255) NULL,
  `genero` VARCHAR(255) NULL,
  `metaPrincipal` VARCHAR(255) NULL,
  `modeloCiclo` VARCHAR(255) NULL,
  `data_inicio` DATE NULL,
  `data_termino` DATE NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`idaluno_ciclo`, `idaluno`),
  INDEX `fk_aluno_ciclo_aluno1_idx` (`idaluno` ASC),
  CONSTRAINT `fk_aluno_ciclo_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `academia`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno_ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno_ciclo` (
  `idaluno_ciclo` INT NOT NULL AUTO_INCREMENT,
  `idaluno` INT NOT NULL,
  `ciclo` VARCHAR(255) NULL,
  `nivel` VARCHAR(255) NULL,
  `genero` VARCHAR(255) NULL,
  `metaPrincipal` VARCHAR(255) NULL,
  `modeloCiclo` VARCHAR(255) NULL,
  `data_inicio` DATE NULL,
  `data_termino` DATE NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`idaluno_ciclo`, `idaluno`),
  INDEX `fk_aluno_ciclo_aluno1_idx` (`idaluno` ASC),
  CONSTRAINT `fk_aluno_ciclo_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `academia`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno_treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno_treino` (
  `idaluno_treino` INT NOT NULL AUTO_INCREMENT,
  `idaluno_ciclo` INT NOT NULL,
  `treino` VARCHAR(255) NULL,
  `regioesTrabalhadas` VARCHAR(255) NULL,
  PRIMARY KEY (`idaluno_treino`, `idaluno_ciclo`),
  INDEX `fk_aluno_treino_aluno_ciclo1_idx` (`idaluno_ciclo` ASC),
  CONSTRAINT `fk_aluno_treino_aluno_ciclo1`
    FOREIGN KEY (`idaluno_ciclo`)
    REFERENCES `academia`.`aluno_ciclo` (`idaluno_ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno_exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno_exercicio` (
  `idaluno_exercicio` INT NOT NULL AUTO_INCREMENT,
  `idaluno_treino` INT NOT NULL,
  `exercicio` VARCHAR(255) NULL,
  `regiaoTrabalhada` VARCHAR(255) NULL,
  `tipoExercicio` VARCHAR(255) NULL,
  `aparelho` VARCHAR(255) NULL,
  `serie` VARCHAR(255) NULL,
  `repeticao` VARCHAR(255) NULL,
  `peso` VARCHAR(255) NULL,
  `intervalo` VARCHAR(255) NULL,
  PRIMARY KEY (`idaluno_exercicio`, `idaluno_treino`),
  INDEX `fk_aluno_exercicio_aluno_treino1_idx` (`idaluno_treino` ASC),
  CONSTRAINT `fk_aluno_exercicio_aluno_treino1`
    FOREIGN KEY (`idaluno_treino`)
    REFERENCES `academia`.`aluno_treino` (`idaluno_treino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno_regiao_trabalhada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno_regiao_trabalhada` (
  `idaluno_regiao_trabalhada` INT NOT NULL AUTO_INCREMENT,
  `regiaoTrabalhada` VARCHAR(255) NULL,
  PRIMARY KEY (`idaluno_regiao_trabalhada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno_aparelho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno_aparelho` (
  `idaluno_aparelho` INT NOT NULL AUTO_INCREMENT,
  `aparelho` VARCHAR(255) NULL,
  `numero` VARCHAR(255) NULL,
  `aluno_aparelhocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idaluno_aparelho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno_tipo_exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno_tipo_exercicio` (
  `idaluno_tipo_exercicio` INT NOT NULL AUTO_INCREMENT,
  `tipoExercicio` VARCHAR(255) NULL,
  PRIMARY KEY (`idaluno_tipo_exercicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`treino_realizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`treino_realizado` (
  `idtreino_realizado` INT NOT NULL AUTO_INCREMENT,
  `idaluno_treino` INT NOT NULL,
  `data_treino` DATE NULL,
  PRIMARY KEY (`idtreino_realizado`, `idaluno_treino`),
  INDEX `fk_treino_realizado_aluno_treino1_idx` (`idaluno_treino` ASC),
  CONSTRAINT `fk_treino_realizado_aluno_treino1`
    FOREIGN KEY (`idaluno_treino`)
    REFERENCES `academia`.`aluno_treino` (`idaluno_treino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`exercicio_realizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`exercicio_realizado` (
  `idexercicio_realizado` INT NOT NULL AUTO_INCREMENT,
  `idtreino_realizado` INT NOT NULL,
  `idaluno_exercicio` INT NOT NULL,
  PRIMARY KEY (`idexercicio_realizado`, `idtreino_realizado`, `idaluno_exercicio`),
  INDEX `fk_exercicio_realizado_treino_realizado1_idx` (`idtreino_realizado` ASC),
  INDEX `fk_exercicio_realizado_aluno_exercicio1_idx` (`idaluno_exercicio` ASC),
  CONSTRAINT `fk_exercicio_realizado_treino_realizado1`
    FOREIGN KEY (`idtreino_realizado`)
    REFERENCES `academia`.`treino_realizado` (`idtreino_realizado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercicio_realizado_aluno_exercicio1`
    FOREIGN KEY (`idaluno_exercicio`)
    REFERENCES `academia`.`aluno_exercicio` (`idaluno_exercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`alteracoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`alteracoes` (
  `idalteracao` INT NOT NULL AUTO_INCREMENT,
  `alteracao` VARCHAR(255) NULL,
  `idpessoa` INT NOT NULL,
  `dataAlteracao` DATE NULL,
  PRIMARY KEY (`idalteracao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`avaliacao_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`avaliacao_fisica` (
  `idavaliacao_fisica` INT NOT NULL AUTO_INCREMENT,
  `idaluno` INT NOT NULL,
  `data_avaliacao` DATE NULL,
  `peso` FLOAT NULL,
  `altura` FLOAT NULL,
  `triceps` FLOAT NULL,
  `subescapular` FLOAT NULL,
  `supralliaca` FLOAT NULL,
  `abdomen` FLOAT NULL,
  `braco_esquerdo` FLOAT NULL,
  `braco_direito` FLOAT NULL,
  `antibraco_esquerdo` FLOAT NULL,
  `antibraco_direito` FLOAT NULL,
  `quadril` FLOAT NULL,
  `cintura` FLOAT NULL,
  `pescoco` FLOAT NULL,
  `coxa_esquerda` FLOAT NULL,
  `coxa_direita` FLOAT NULL,
  `perna_esquerda` FLOAT NULL,
  `perna_direita` FLOAT NULL,
  `radio` FLOAT NULL,
  `femur` FLOAT NULL,
  `imc` FLOAT NULL,
  `percentual_gordura` FLOAT NULL,
  `massa_magra` FLOAT NULL,
  `massa_gorda` FLOAT NULL,
  `idcadastrador` INT NOT NULL,
  `dataCadastro` DATE NULL,
  PRIMARY KEY (`idavaliacao_fisica`, `idaluno`),
  INDEX `fk_avaliacao_fisica_aluno1_idx` (`idaluno` ASC),
  CONSTRAINT `fk_avaliacao_fisica_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `academia`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`refeicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`refeicao` (
  `idrefeicao` INT NOT NULL AUTO_INCREMENT,
  `refeicao` VARCHAR(255) NULL,
  PRIMARY KEY (`idrefeicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`plano_nutricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`plano_nutricao` (
  `idplano_nutricao` INT NOT NULL AUTO_INCREMENT,
  `idaluno` INT NOT NULL,
  `plano` VARCHAR(255) NULL,
  `idcadastrador` INT NULL,
  `dataCadastro` DATE NULL,
  `data_inicio` DATE NULL,
  `data_termino` DATE NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`idplano_nutricao`, `idaluno`),
  INDEX `fk_plano_nutricao_aluno1_idx` (`idaluno` ASC),
  CONSTRAINT `fk_plano_nutricao_aluno1`
    FOREIGN KEY (`idaluno`)
    REFERENCES `academia`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`refeicao_plano_nutricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`refeicao_plano_nutricao` (
  `idrefeicao_plano_nutricao` INT NOT NULL AUTO_INCREMENT,
  `idplano_nutricao` INT NOT NULL,
  `idrefeicao` INT NOT NULL,
  `horario` TIME NULL,
  PRIMARY KEY (`idrefeicao_plano_nutricao`, `idplano_nutricao`, `idrefeicao`),
  INDEX `fk_refeicao_plano_nutricao_plano_nutricao1_idx` (`idplano_nutricao` ASC),
  INDEX `fk_refeicao_plano_nutricao_refeicao1_idx` (`idrefeicao` ASC),
  CONSTRAINT `fk_refeicao_plano_nutricao_plano_nutricao1`
    FOREIGN KEY (`idplano_nutricao`)
    REFERENCES `academia`.`plano_nutricao` (`idplano_nutricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_refeicao_plano_nutricao_refeicao1`
    FOREIGN KEY (`idrefeicao`)
    REFERENCES `academia`.`refeicao` (`idrefeicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`alimento` (
  `idalimento` INT NOT NULL AUTO_INCREMENT,
  `idrefeicao_plano_nutricao` INT NOT NULL,
  `alimento` VARCHAR(255) NULL,
  `medida` VARCHAR(255) NULL,
  PRIMARY KEY (`idalimento`, `idrefeicao_plano_nutricao`),
  INDEX `fk_alimento_refeicao_plano_nutricao1_idx` (`idrefeicao_plano_nutricao` ASC),
  CONSTRAINT `fk_alimento_refeicao_plano_nutricao1`
    FOREIGN KEY (`idrefeicao_plano_nutricao`)
    REFERENCES `academia`.`refeicao_plano_nutricao` (`idrefeicao_plano_nutricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`horario` (
  `idhorario` INT NOT NULL AUTO_INCREMENT,
  `horario` TIME NULL,
  PRIMARY KEY (`idhorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`permissao` (
  `idpermissao` INT NOT NULL AUTO_INCREMENT,
  `permissao` VARCHAR(255) NULL,
  PRIMARY KEY (`idpermissao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`usuario_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`usuario_permissao` (
  `idusuario_permissao` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idpermissao` INT NOT NULL,
  `visualizar` TINYINT(1) NULL,
  `cadastrar` TINYINT(1) NULL,
  `alterar` TINYINT(1) NULL,
  `excluir` TINYINT(1) NULL,
  PRIMARY KEY (`idusuario_permissao`, `idusuario`, `idpermissao`),
  INDEX `fk_permissao_has_usuario_usuario1_idx` (`idusuario` ASC, `idusuario_permissao` ASC),
  INDEX `fk_permissao_has_usuario_permissao1_idx` (`idpermissao` ASC),
  CONSTRAINT `fk_permissao_has_usuario_permissao1`
    FOREIGN KEY (`idpermissao`)
    REFERENCES `academia`.`permissao` (`idpermissao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permissao_has_usuario_usuario1`
    FOREIGN KEY (`idusuario` , `idusuario_permissao`)
    REFERENCES `academia`.`usuario` (`idusuario` , `idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `academia` ;

-- -----------------------------------------------------
-- Placeholder table for view `academia`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `academia`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academia`.`view1`;
USE `academia`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
